export const fonts: readonly { label: string; value: string }[] = [
  { label: "Arial", value: "Arial" },
  { label: "Arial Black", value: "Arial Black" },
  { label: "Helvetica", value: "Helvetica" },
  { label: "Times New Roman", value: "Times New Roman" },
  { label: "Georgia", value: "Georgia" },
  { label: "Garamond", value: "Garamond" },
  { label: "Courier New", value: "Courier New" },
  { label: "Verdana", value: "Verdana" },
  { label: "Tahoma", value: "Tahoma" },
  { label: "Trebuchet MS", value: "Trebuchet MS" },
  { label: "Comic Sans MS", value: "Comic Sans MS" },
  { label: "Impact", value: "Impact" },
  { label: "Lucida Console", value: "Lucida Console" },
  { label: "Lucida Sans Unicode", value: "Lucida Sans Unicode" },
  { label: "Palatino Linotype", value: "Palatino Linotype" },
  { label: "Segoe UI", value: "Segoe UI" },
  { label: "Calibri", value: "Calibri" },
  { label: "Cambria", value: "Cambria" },
  { label: "Century Gothic", value: "Century Gothic" },
  { label: "Book Antiqua", value: "Book Antiqua" },
  { label: "Franklin Gothic Medium", value: "Franklin Gothic Medium" },
  { label: "Consolas", value: "Consolas" },
  { label: "Monaco", value: "Monaco" },
  { label: "Copperplate", value: "Copperplate" },
  { label: "Brush Script MT", value: "Brush Script MT" },
] as const;
